services:
  - type: web
    name: saas-framework-webhook
    env: node
    plan: free
    rootDir: .
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_API_KEY
        value: webhook-secret-2024-make-com-integration